# MFDS Assignment 1

Gauss Elimintation

In [41]:
import numpy as np
import math
np.set_printoptions(suppress=True)
A = np.random.rand(2,2)
f = np.random.rand(2,1)
# A= np.array([[10,-7,0],[-3,2.099,6],[5,-1,5]])
# f = np.array([[7],[3.901],[6]])
print("Original Random 2x2 Coefficient Matrix A:\n",A)
print("Original Random Vector b :\n",f)

# # Original Random 2x2 Coefficient Matrix A:
# A = np.array([[0.39245808 ,0.42972412], [0.26497132, 0.50848123]])
# f = np.array([[0.0841236 ],[0.78500416]])

Original Random 2x2 Coefficient Matrix A:
 [[0.15633232 0.47083257]
 [0.93532801 0.43520211]]
Original Random Vector b :
 [[0.28983876]
 [0.20437107]]


In [17]:
def convertToSig(a_number,significant_digits):
    if(type(a_number) == np.ndarray):
        for idx,i in  np.ndenumerate(a_number):
            if(a_number[idx]!=0):
                a_number[idx] = round(a_number[idx], significant_digits - int(math.floor(math.log10(abs(a_number[idx])))) - 1)
        return(a_number)    
    elif(a_number != 0.):
        rounded_number =  round(a_number, significant_digits - int(math.floor(math.log10(abs(a_number)))) - 1)
        return(rounded_number)
    else:
        return(a_number)

In [3]:
def GaussElimWithPivot(A, f,digits):
    A=np.around(A,digits)
    f=np.around(f,digits)
    print("Executing 2x2 system of equations with Pivot for ",digits," significant digits!!\n\n")

    print("Random 2x2 Coefficient Matrix A of ",digits," significant digits:\n",A)
    print("Random Vector b of ",digits," significant digits:\n",f)
   
    print("Equations which must be solved based on above matrix:")
    for i in range(A.shape[0]):
        row = ["{}*x{}".format(A[i, j], j + 1) for j in range(A.shape[1])]
        print("[{}] = [{}]".format(" + ".join(row), f[i]))
 #Caluculating the LU using Pivoting
    n = len(f)
    for i in range(0,n-1):     # Step - Looping through the columns of the matrix
        if np.abs(A[i,i])==0:
            for k in range(i+1,n):
                if np.abs(A[k,i])>np.abs(A[i,i]):
                    A[[i,k]]=A[[k,i]]             # Step Swapping ith and kth rows to each other
                    f[[i,k]]=f[[k,i]]
                    break
        for j in range(i+1,n):     # Loop through rows below diagonal for each column
            m = convertToSig(A[j,i]/A[i,i],digits)
            A[j,:] = convertToSig(A[j,:] - convertToSig(m*A[i,:],digits),digits)
            f[j] = convertToSig(f[j] - convertToSig(m*f[i],digits),digits)        
 #Caluculating the final output
    n = f.size
    x = np.zeros(n)             # Initialize the solution vector, x, to zero
    x[n-1] = convertToSig(f[n-1]/A[n-1,n-1],digits)    # Solve for last entry first
    for i in range(n-2,-1,-1):      # Loop from the end to the beginning
        sum_ = 0
        for j in range(i+1,n):        # For known x values, sum and move to rhs
            sum_ = convertToSig(sum_ + A[i,j]*x[j],digits)
        sum_ = convertToSig(sum_,digits)
        x[i] = convertToSig((f[i] - sum_)/A[i,i],digits)
    print("Solution is as below:")
    return x

In [4]:
def GaussElimWithoutPivot(A, f,digits):
    print("Executing 2x2 system of equations without Pivot for ",digits," significant digits!!\n")
    A = np.around(A,digits)
    f = np.around(f,digits)
    print("Random 2x2 Coefficient Matrix A of ",digits," significant digits:\n",A)
    print("Random Vector b of ",digits," significant digits:\n",f)
    
    print("Equations which must be solved based on above matrix:")
    for i in range(A.shape[0]):
        row = ["{}*x{}".format(A[i, j], j + 1) 
        for j in range(A.shape[1])]
        print("[{}] = [{}]".format(" + ".join(row), f[i]))
    #LU Decomposition with no pivoting
    n = len(f)
    for i in range(0,n-1):     # Loop through the columns of the matrix
        for j in range(i+1,n):     # Loop through rows below diagonal for each column
            if A[i,i] == 0:
                print("Error: Zero on diagonal!")
                print("Need algorithm with pivoting")
                break
            m = convertToSig(A[j,i]/A[i,i],digits)
            A[j,:] = convertToSig(A[j,:] - convertToSig(m*A[i,:],digits),digits)
            f[j] = convertToSig(f[j] - convertToSig(m*f[i],digits),digits)
    #Using Back Substitution
    n = f.size
    x = np.zeros(n)             # Initialize the solution vector, x, to zero
    x[n-1] = convertToSig(f[n-1]/A[n-1,n-1],digits)   # Solve for last entry first
    for i in range(n-2,-1,-1):      # Loop from the end to the beginning
        sum_ = 0
        for j in range(i+1,n):        # For known x values, sum and move to rhs
            sum_ =convertToSig(sum_ + convertToSig(A[i,j]*x[j],digits),digits)
        x[i] = convertToSig(((f[i] - sum_)/A[i,i]),digits)
    print("\nSolution is as below:")
    return x

In [42]:
print(GaussElimWithoutPivot(A,f,3))

Executing 2x2 system of equations without Pivot for  3  significant digits!!

Random 2x2 Coefficient Matrix A of  3  significant digits:
 [[0.156 0.471]
 [0.935 0.435]]
Random Vector Matrix B of  3  significant digits:
 [[0.29 ]
 [0.204]]
Equations which must be solved based on above matrix:
[0.156*x1 + 0.471*x2] = [[0.29]]
[0.935*x1 + 0.435*x2] = [[0.204]]

Solution is as below:
[-0.0962  0.647 ]


In [43]:
print(GaussElimWithPivot(A,f,3))

Executing 2x2 system of equations with Pivot for  3  significant digits!!


Random 2x2 Coefficient Matrix A of  3  significant digits:
 [[0.156 0.471]
 [0.935 0.435]]
Random Vector Matrix B of  3  significant digits:
 [[0.29 ]
 [0.204]]
Equations which must be solved based on above matrix:
[0.156*x1 + 0.471*x2] = [[0.29]]
[0.935*x1 + 0.435*x2] = [[0.204]]
Solution is as below:
[-0.0962  0.647 ]


In [44]:
print(GaussElimWithoutPivot(A,f,4))

Executing 2x2 system of equations without Pivot for  4  significant digits!!

Random 2x2 Coefficient Matrix A of  4  significant digits:
 [[0.1563 0.4708]
 [0.9353 0.4352]]
Random Vector Matrix B of  4  significant digits:
 [[0.2898]
 [0.2044]]
Equations which must be solved based on above matrix:
[0.1563*x1 + 0.4708*x2] = [[0.2898]]
[0.9353*x1 + 0.4352*x2] = [[0.2044]]

Solution is as below:
[-0.08061  0.6423 ]


In [45]:
print(GaussElimWithPivot(A,f,4))

Executing 2x2 system of equations with Pivot for  4  significant digits!!


Random 2x2 Coefficient Matrix A of  4  significant digits:
 [[0.1563 0.4708]
 [0.9353 0.4352]]
Random Vector Matrix B of  4  significant digits:
 [[0.2898]
 [0.2044]]
Equations which must be solved based on above matrix:
[0.1563*x1 + 0.4708*x2] = [[0.2898]]
[0.9353*x1 + 0.4352*x2] = [[0.2044]]
Solution is as below:
[-0.08061  0.6423 ]


In [46]:
print(GaussElimWithoutPivot(A,f,5))

Executing 2x2 system of equations without Pivot for  5  significant digits!!

Random 2x2 Coefficient Matrix A of  5  significant digits:
 [[0.15633 0.47083]
 [0.93533 0.4352 ]]
Random Vector Matrix B of  5  significant digits:
 [[0.28984]
 [0.20437]]
Equations which must be solved based on above matrix:
[0.15633*x1 + 0.47083*x2] = [[0.28984]]
[0.93533*x1 + 0.4352*x2] = [[0.20437]]

Solution is as below:
[-0.080279  0.64225 ]


In [47]:
print(GaussElimWithPivot(A,f,5))

Executing 2x2 system of equations with Pivot for  5  significant digits!!


Random 2x2 Coefficient Matrix A of  5  significant digits:
 [[0.15633 0.47083]
 [0.93533 0.4352 ]]
Random Vector Matrix B of  5  significant digits:
 [[0.28984]
 [0.20437]]
Equations which must be solved based on above matrix:
[0.15633*x1 + 0.47083*x2] = [[0.28984]]
[0.93533*x1 + 0.4352*x2] = [[0.20437]]
Solution is as below:
[-0.080279  0.64225 ]


In [49]:
print(GaussElimWithoutPivot(A,f,6))

Executing 2x2 system of equations without Pivot for  6  significant digits!!

Random 2x2 Coefficient Matrix A of  6  significant digits:
 [[0.156332 0.470833]
 [0.935328 0.435202]]
Random Vector Matrix B of  6  significant digits:
 [[0.289839]
 [0.204371]]
Equations which must be solved based on above matrix:
[0.156332*x1 + 0.470833*x2] = [[0.289839]]
[0.935328*x1 + 0.435202*x2] = [[0.204371]]

Solution is as below:
[-0.0803418  0.642263 ]


In [50]:
print(GaussElimWithPivot(A,f,6))

Executing 2x2 system of equations with Pivot for  6  significant digits!!


Random 2x2 Coefficient Matrix A of  6  significant digits:
 [[0.156332 0.470833]
 [0.935328 0.435202]]
Random Vector Matrix B of  6  significant digits:
 [[0.289839]
 [0.204371]]
Equations which must be solved based on above matrix:
[0.156332*x1 + 0.470833*x2] = [[0.289839]]
[0.935328*x1 + 0.435202*x2] = [[0.204371]]
Solution is as below:
[-0.0803418  0.642263 ]


Q2:


In [69]:
import numpy as np
def getRandomMatrix():
    return np.around(np.random.randn(3,3),4)
def getLUMatrices(A):
    n = A.shape[0]
    U = A.copy()
    L = np.eye(n, dtype=np.double)
    for i in range(n):
        factor = U[i+1:, i] / U[i, i]
        L[i+1:, i] = factor
        U[i+1:] -= factor[:, np.newaxis] * U[i]
    return L, U
def generate_diagonally_dominant_matrix():
    A = getRandomMatrix()
    D = np.diag(np.abs(A)) # Find diagonal coefficients
    S = np.sum(np.abs(A), axis=1) - D # Find row sum without diagonal
    L,U = getLUMatrices(A)
    C = -np.linalg.inv(np.identity(3)+L)*U
    if np.all(D > S) and np.linalg.norm(C,'fro') < 1:
        return A
    else:
        return generate_diagonally_dominant_matrix()
def testConvrgence(A):
    L,U = getLUMatrices(A)
    C = -np.linalg.inv(np.identity(3)+L)*U
    print("Test for convergence::",np.linalg.norm(C,'fro') < 1)
    
A = generate_diagonally_dominant_matrix()
b = np.random.rand(3,1)
print("Random Generated Co-efficient matrix is:\n",A)
print("Random Generated Vector is:\n",b)


Random Generated Co-efficient matrix is:
 [[-1.1085  0.225   0.2349]
 [ 0.812  -1.215   0.1021]
 [ 0.3156  0.0211  1.0126]]
Random Generated Vector is:
 [[0.83064534]
 [0.02931809]
 [0.12890841]]


In [64]:
def GaussJacobiSolution(A,b):
    ITERATION_LIMIT = 1000

    # prints the system
    print("System of equations to be solved using Gauss Jacobi:")
    for i in range(A.shape[0]):
        row = ["{}x{}".format(A[i, j], j + 1) for j in range(A.shape[1])]
        print(" + ".join(row), "=", b[i])
    print()

    x = np.zeros_like(b)
    for it_count in range(ITERATION_LIMIT):
        if it_count != 0:
            print("Iteration {0}: {1}".format(it_count, x))
        x_new = np.zeros_like(x)

        for i in range(A.shape[0]):
            s1 = np.dot(A[i, :i], x[:i])
            s2 = np.dot(A[i, i + 1:], x[i + 1:])
            x_new[i] = (b[i] - s1 - s2) / A[i, i]
            if x_new[i] == x_new[i-1]:
                break

        if np.allclose(x, x_new, atol=0.01, rtol=0.):
            break

        x = x_new

    print("Solution:")
    print(x)
    error = np.dot(A, x) - b
    print("Error:")
    print(error)

In [63]:

def GaussSeidelSolution(A,b):
    ITERATION_LIMIT = 1000

    # prints the system
    print("System of equations to be solved using Gauss ssiedel:")
    for i in range(A.shape[0]):
        row = ["{}x{}".format(A[i, j], j + 1) for j in range(A.shape[1])]
        print("[{}] = [{}]".format(" + ".join(row), b[i]))

    x = np.zeros_like(b)
    for it_count in range(1, ITERATION_LIMIT):
        x_new = np.zeros_like(x)
        print("Iteration {0}: {1}".format(it_count, x))
        for i in range(A.shape[0]):
            s1 = np.dot(A[i, :i], x_new[:i])
            s2 = np.dot(A[i, i + 1 :], x[i + 1 :])
            x_new[i] = (b[i] - s1 - s2) / A[i, i]
        if np.allclose(x, x_new, rtol=0.01):
            break
        x = x_new

    print("Solution: {0}".format(x))
    error = np.dot(A, x) - b
    print("Error: {0}".format(error))

In [70]:
GaussJacobiSolution(A,b)

System of equations to be solved using Gauss Jacobi:
-1.1085x1 + 0.225x2 + 0.2349x3 = [0.83064534]
0.812x1 + -1.215x2 + 0.1021x3 = [0.02931809]
0.3156x1 + 0.0211x2 + 1.0126x3 = [0.12890841]

Iteration 1: [[-0.74934175]
 [-0.02413012]
 [ 0.12730438]]
Iteration 2: [[-0.7272628 ]
 [-0.51422701]
 [ 0.36135672]]
Iteration 3: [[-0.77714363]
 [-0.47980326]
 [ 0.36468768]]
Iteration 4: [[-0.76945055]
 [-0.51285935]
 [ 0.37951688]]
Solution:
[[-0.76945055]
 [-0.51285935]
 [ 0.37951688]]
Error:
[[-0.00395424]
 [ 0.00776085]
 [ 0.00173045]]


In [71]:
GaussSeidelSolution(A,b)

System of equations to be solved using Gauss ssiedel:
[-1.1085x1 + 0.225x2 + 0.2349x3] = [[0.83064534]]
[0.812x1 + -1.215x2 + 0.1021x3] = [[0.02931809]]
[0.3156x1 + 0.0211x2 + 1.0126x3] = [[0.12890841]]
Iteration 1: [[0.]
 [0.]
 [0.]]
Iteration 2: [[-0.74934175]
 [-0.52492477]
 [ 0.37179201]]
Iteration 3: [[-0.77710371]
 [-0.51223567]
 [ 0.38018025]]
Solution: [[-0.77710371]
 [-0.51223567]
 [ 0.38018025]]
Error: [[0.00482545]
 [0.00085644]
 [0.        ]]


In [56]:
#Generate Non Diagonally Dominant Random Matrix 
def generateNDD():
    A = getRandomMatrix()
    D = np.diag(np.abs(A)) # Find diagonal coefficients
    S = np.sum(np.abs(A), axis=1) - D # Find row sum without diagonal
    if all(D < S):
        return A
    else:
        return generateNDD()
def is_pos_def(x):
    return np.all(np.linalg.eigvals(x) > 0)

In [57]:
AA = generateNDD()
if is_pos_def(AA):
    AA = generateNDD()
print("Non Diagonally Dominant Random Matrix is:\n",AA)

Non Diagonally Dominant Random Matrix is:
 [[ 1.575  -2.3733  0.2185]
 [ 0.4997 -1.3198  1.2499]
 [-0.9716 -0.0028 -0.7973]]


In [72]:
def NDDSolutionAttempt(AA,b):
    ITERATION_LIMIT = 1000

    # prints the system
    print("System of equations to be solved using Non Diagonally Dominant Random Matrix:")
    for i in range(AA.shape[0]):
        row = ["{}x{}".format(AA[i, j], j + 1) for j in range(AA.shape[1])]
        print(" + ".join(row), "=", b[i])
    print()

    x = np.zeros_like(b)
    for it_count in range(ITERATION_LIMIT):
        if it_count != 0:
            print("Iteration {0}: {1}".format(it_count, x))
        x_new = np.zeros_like(x)

        for i in range(AA.shape[0]):
            s1 = np.dot(AA[i, :i], x[:i])
            s2 = np.dot(AA[i, i + 1:], x[i + 1:])
            x_new[i] = (b[i] - s1 - s2) / AA[i, i]
            if x_new[i] == x_new[i-1]:
                break

        if np.allclose(x, x_new, atol=0.01, rtol=0.):
            break

        x = x_new

    print("Solution:")
    print(x)
    error = np.dot(AA, x) - b
    print("Error:")
    print(error)

In [73]:
NDDSolutionAttempt(AA,b)

System of equations to be solved using Non Diagonally Dominant Random Matrix:
1.575x1 + -2.3733x2 + 0.2185x3 = [0.83064534]
0.4997x1 + -1.3198x2 + 1.2499x3 = [0.02931809]
-0.9716x1 + -0.0028x2 + -0.7973x3 = [0.12890841]

Iteration 1: [[ 0.52739386]
 [-0.02221404]
 [-0.16168119]]
Iteration 2: [[ 0.51635053]
 [ 0.02434861]
 [-0.8042921 ]]
Iteration 3: [[ 0.67566332]
 [-0.58840918]
 [-0.79099808]]
Iteration 4: [[-0.24951942]
 [-0.51550056]
 [-0.98298676]]
Iteration 5: [[-0.11302192]
 [-1.04761184]
 [ 0.14419673]]
Iteration 6: [[-1.07121195]
 [ 0.07155353]
 [-0.02027217]]
Iteration 7: [[ 0.63802717]
 [-0.44699264]
 [ 1.14346013]]
Iteration 8: [[-0.3047926 ]
 [ 1.30225406]
 [-0.93761951]]
Iteration 9: [[ 2.61978079]
 [-1.02557477]
 [ 0.20516965]]
Iteration 10: [[-1.04646402]
 [ 1.16398539]
 [-3.35057798]]
Iteration 11: [[ 2.74617978]
 [-3.59154689]
 [ 1.10946553]]
Iteration 12: [[-5.03847055]
 [ 2.06824436]
 [-3.49559809]]
Iteration 13: [[ 4.12888753]
 [-5.24033178]
 [ 5.97100023]]
Iteratio

Iteration 707: [[ 1.65738348e+103]
 [-1.41327783e+103]
 [ 1.43402761e+103]]
Iteration 708: [[-2.32855067e+103]
 [ 1.98559299e+103]
 [-2.01474553e+103]]
Iteration 709: [[ 3.27151095e+103]
 [-2.78967056e+103]
 [ 2.83062858e+103]]
Iteration 710: [[-4.59632856e+103]
 [ 3.91936406e+103]
 [-3.97690827e+103]]
Iteration 711: [[ 6.45763884e+103]
 [-5.50653359e+103]
 [ 5.58738067e+103]]
Iteration 712: [[-9.07269768e+103]
 [ 7.73643675e+103]
 [-7.85002334e+103]]
Iteration 713: [[ 1.27467400e+104]
 [-1.08693523e+104]
 [ 1.10289365e+104]]
Iteration 714: [[-1.79086073e+104]
 [ 1.52709605e+104]
 [-1.54951692e+104]]
Iteration 715: [[ 2.51608032e+104]
 [-2.14550258e+104]
 [ 2.17700290e+104]]
Iteration 716: [[-3.53498184e+104]
 [ 3.01433646e+104]
 [-3.05859304e+104]]
Iteration 717: [[ 4.96649353e+104]
 [-4.23500974e+104]
 [ 4.29718828e+104]]
Iteration 718: [[-6.97770429e+104]
 [ 5.95000185e+104]
 [-6.03735994e+104]]
Iteration 719: [[ 9.80336669e+104]
 [-8.35949010e+104]
 [ 8.48222437e+104]]
Iteration 72